### PR TITLE
Validation for response in ff58

### LINKED ISSUE #139: Leadfoot throws TypeError when trying to launch new FF 58 with GeckoDriver 19.1
Environment:

Mac OSX 10.3.3
Node.js - 6.12.2
Leadfoot: 1.7.4  - 2.0.0 beta 8
Browser: Firefox 58
GeckoDriver: 19.1

1.) Use leadfoot directly to start browser
2.) Use standard capabilities

Expected Result:
Browser starts with capabilities

Actual Result: 
Browser fails to start with stack trace:

RROR  TypeError: Cannot read property 'platform' of undefined
           at Server._fillCapabilities (/Users/silne30/Desktop/kibana/node_modules/leadfoot/Server.js:395:19)
           at /Users/silne30/Desktop/kibana/test/functional/services/remote/leadfoot_command.js:33:18
           at undefined.next (native)
           at step (/Users/silne30/Desktop/kibana/test/functional/services/remote/leadfoot_command.js:104:191)
           at /Users/silne30/Desktop/kibana/test/functional/services/remote/leadfoot_command.js:104:361
           at process._tickDomainCallback (internal/process/next_tick.js:135:7)

### PR DESCRIPTION
**Pull request by silne30**
Fixes #139

### CODE REVIEW

**Comment by silne30** [comment]
@dylans I did sign it. Not sure why it's still saying I haven't.
screen shot 2018-03-15 at 5 23 59 pm

**Comment by dylans** [comment]
Usually when this issue pops up, it's a mismatch between the email address in the commit and in the CLA

**Comment by silne30** [comment]
@dylans Right. That second set of commits I did was editing the author of those commits. So they are all under the new email address.

**Comment by dylans** [comment]
But that doesn't appear to be the case. It will either clear up on its own or you might want to try closing and reopening the PR to trigger a new CLA check

**Comment by silne30** [comment]
Gotcha.

**Pull request closed without merging**
